import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { AppSidebar } from "@/components/app-sidebar";
import AppHeader from "@/components/app-header";
import CustomProvider from "@/components/providers/custom-proivider";
import { SidebarInset } from "@/components/ui/sidebar";
import NextTopLoader from "nextjs-toploader";
import { Toaster } from "@/components/ui/sonner";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "LendRents Manager",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextTopLoader />
        <CustomProvider>
          <AppSidebar /> 
          <SidebarInset>
            <main className="w-full flex">
              <div className="flex flex-col w-full pb-20 md:pb-0">
                <AppHeader /> 
                {children}
              </div>
            </main>
          </SidebarInset>
          <Toaster richColors position="top-right" theme="light" />
        </CustomProvider>
      </body>
    </html>
  );
}
