import type {Metadata} from "next";
import localFont from "next/font/local";
import "./globals.css";
import {AppSidebar} from "@/components/app-sidebar";
import AppHeader from "@/components/app-header";
import CustomProvider from "@/components/providers/custom-proivider";
import Head from "next/head";
import {SidebarInset} from "@/components/ui/sidebar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "LendRents Manager",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" href="../assests/favicon_io/favicon.ico" sizes="any" />
      </Head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CustomProvider>
          <AppSidebar />
          <SidebarInset>
            <main className="w-full flex">
              <div className="flex flex-col w-full">
                <AppHeader />
                {children}
              </div>
            </main>
          </SidebarInset>
        </CustomProvider>
      </body>
    </html>
  );
}
